### ISSUE TITLE
Publicar paquete en CRAN

### ISSUE THREAD

**Issue by FvD** [ixpantia/gitear#105]

**Comment by pa00gz** [comment]
`rhub::check_for_cran(email = "", env_vars = c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`

Usando esto pude correr el checkk correctamente

**Comment by FvD** [comment]
![image](https://user-images.githubusercontent.com/2441145/91361264-28555800-e7b5-11ea-9449-38ff12e61b26.png)
