### ISSUE TITLE
Issues do not have projects?

### ISSUE THREAD

**Issue by ekianjo** [ixpantia/gitear#121]
HI, very nice to see the existence of gitear - however I noticed that there is no field for "projects" in issues, is that something you can consider adding?
Thanks!

**Comment by FvD** [comment]
Hi @ekianjo Thank you for your interest in `gitear`. We are gearing up for a next sprint and we will consider adding this field. I will keep the issue open in the meantime.

**Comment by FvD** [comment]
I've checked, and I think that the funcionality you are looking for is already there. Just run the `get_issues()` function with the `full_info` parameter set to `TRUE`. Like so.

```
get_issues(base_url = "https://example.gitea.service.com",
           api_key = "ccaf5c9a22e854856d0c5b1b96c81e851bafb288",
           owner = "company",
           repo = "test_repo",
           full_info = TRUE)
```

You will now have the columns "repository.owner", that is equivalent to the "project" field in the UI.

It's been a long time! I apologize for responding so late. If you have the chance to test and see if this works for you, please let us know.
