### ISSUE TITLE
Funicion get_issues solo trae issues abiertos

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/gitear#40]
Al usar la función get_issues() los datos obtenidos son aquellos que corresponden solamente a los issues que se encuentran abiertos dejando por fuera los que se encuentran cerrados.

¿Hay alguna manera de incluir los issues cerrados dentro del contenido que traemos con get_issues o debe de estar en otra función?

**Comment by FvD** [comment]
Parece que por defecto el endpoint trae los incidentes abiertos, y al incluir `?state=closed` vienen los cerrados. Fué por eso que lo implementamos como dos funciones diferentes.
