### ISSUE TITLE
Extraer cantidad de commits por repositorio y por proyecto

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/gitear#52]
Para poder revisar y obtener metricas sobre avance de proyectos seria util poder extraer la informacion de los commits por repositoriosy por proyectos identificados por participante que genero el commit.

**Comment by ronnyhdez** [comment]
Hay un problema con el API de gitea que a pesar de que existen commits creados en el repositorio, el GET trae una lista con cero observaciones.

Parte del problema está descrito en el issue de go-gitea/gitea#5181.

**Comment by HoffmannP** [comment]
Could you please speake english here?
¡En inglés por favor!

**Comment by pa00gz** [comment]
La función `get_commits()` trae todos lommits de un repositorio y un proyecto especifico. Actualmente funciona para la version del API gitea 1.1.1
