### ISSUE TITLE
Extender documentación función add_tracked_time_issue

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/gitear#63]
En la documentación existente no queda bien claro cómo se deben de escribir los parámetros o dónde obtenerlos. 

**base_url**	
The base URL for your gitea server (no trailing '/')
**api_key**	
The user's API token key for the gitea service
**owner**	
The owner of the repo
**repo**	
The name of the repo
**id_issue**	
Index of the issue to add tracked time to
**time**	
The time to add the issue

**Comment by pa00gz** [comment]
La documentación ahora es un poco más explícita
