### ISSUE TITLE
Revisar dataframe que regresa la función get_issues_open_state()

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/gitear#68]
Si bien la función trae como respuesta un dataframe, hay dos variables que siguen como una lista: **labels** y **assignees**.

Hay que verificar si este es un comportamiendo deseado o si bien hay que corregirlo.

**Comment by pa00gz** [comment]
Acordamos no incluir esto. Además la información de assignees ya viene en otras columnas, y aparte de esto hay una función para consultar los labels de un tiquete si eso es lo que se quiere ver.
