### ISSUE TITLE
Especificar parámetro organización en función get_list_org_team()

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/gitear#69]
En documentación se ha venido manejando el nombre **owner** para hacer referencia a lo que tenemos como el proyecto bajo el cual colocamos varios repositorios concernientes a un tema en específico. En esta función el argumento org parece que hace alusión a lo mismo, por lo que sería recomendable unificar términos que se refieran al mismo objeto.

**Comment by FvD** [comment]
Creo que no es lo mismo. Si tengo una organizacion (un proyecto) llamado `foo` con el repositorio `bar` tendria el url gitear.org/foo/bar. En el momento que hago una bifurcacion quedo con gitear.org/frans/bar. Ahora la "organizacion" es `frans` y eso es  lo que vez en esa columna.

**Comment by pa00gz** [comment]
Exactamente. Una organizacion es lo que nosotros conocemos como proyecto, y un owner es el dueño del repositorio. La organización puede ser un owner como lo es el caso de este repositorio, que ixpantia es una organización pero tambien es un owner, sin embargo eso no quiere decir que sea lo mismo.
