### ISSUE TITLE
Refactorizar org por project en las funciones

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/gitear#84]
Dentro de ixplorer usamos proyectos bajo los cuales creamos repositorios. Dentro de todas las funciones los proyectos están referidos como org, lo cual hace confuso su uso.

**Comment by FvD** [comment]
Es valido el punto, pero queremos que este paquete tenga uso publico. Creo que tiene más sentido si lo dejamos como `org` ya que ese es el lenguaje que se usa dentro de gitea.
